name: Code quality check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  ci-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # install bun
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install bun dependencies
        run: bun install

      - name: Check linting backend
        run: cargo clippy --manifest-path ./backend/Cargo.toml

      - name: Check linting frontend
        run: bun --cwd frontend biome check

      - name: Check compile
        run: bun run build
